name: Shared Workflow
'on':
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Print environment
      run: echo "Deploying to ${{ inputs.environment }} environment"
